/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

/**
 *
 * @author davidson
 */
public class FormaSatelite extends javax.swing.JFrame {

    /**
     * Creates new form FormaSatelite
     */
    public FormaSatelite() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelSatelite = new javax.swing.JPanel();
        lbNome10 = new javax.swing.JLabel();
        lbEspLuz10 = new javax.swing.JLabel();
        lbGalaxia10 = new javax.swing.JLabel();
        lbMassa10 = new javax.swing.JLabel();
        lbTemperatura10 = new javax.swing.JLabel();
        lbVelocidade10 = new javax.swing.JLabel();
        lbVolume10 = new javax.swing.JLabel();
        lbDiametro10 = new javax.swing.JLabel();
        lbAcGrav10 = new javax.swing.JLabel();
        lbIdade10 = new javax.swing.JLabel();
        tfNome70 = new javax.swing.JTextField();
        tfNome72 = new javax.swing.JTextField();
        tfNome80 = new javax.swing.JTextField();
        lbIdade11 = new javax.swing.JLabel();
        jbVoltar = new javax.swing.JButton();
        tfIdade = new javax.swing.JTextField();
        tfAcelDiametro = new javax.swing.JTextField();
        tfDiametro = new javax.swing.JTextField();
        tfVolume = new javax.swing.JTextField();
        tfVelocidade = new javax.swing.JTextField();
        tfTemperatura = new javax.swing.JTextField();
        tfMassa = new javax.swing.JTextField();
        tfGalaxia = new javax.swing.JTextField();
        jrbArtificial = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelSatelite.setBackground(new java.awt.Color(208, 208, 208));
        painelSatelite.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Satelite", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 18))); // NOI18N

        lbNome10.setText("Nome:");

        lbEspLuz10.setText("Espectro de luz:");

        lbGalaxia10.setText("Galaxia:");

        lbMassa10.setText(" Massa:");

        lbTemperatura10.setText("Temperatura:");

        lbVelocidade10.setText("Velocidade:");

        lbVolume10.setText("Volume:");

        lbDiametro10.setText("Diâmetro:");

        lbAcGrav10.setText("Acel da Gravidade:");

        lbIdade10.setText("Idade:");

        lbIdade11.setText("Distância ao Planeta:");

        jbVoltar.setText("Voltar");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });

        jrbArtificial.setSelected(true);
        jrbArtificial.setText("Artificial");
        jrbArtificial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbArtificialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelSateliteLayout = new javax.swing.GroupLayout(painelSatelite);
        painelSatelite.setLayout(painelSateliteLayout);
        painelSateliteLayout.setHorizontalGroup(
            painelSateliteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSateliteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelSateliteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelSateliteLayout.createSequentialGroup()
                        .addComponent(lbEspLuz10)
                        .addGap(58, 58, 58)
                        .addComponent(tfNome70))
                    .addGroup(painelSateliteLayout.createSequentialGroup()
                        .addComponent(lbNome10)
                        .addGap(123, 123, 123)
                        .addComponent(tfNome72))
                    .addGroup(painelSateliteLayout.createSequentialGroup()
                        .addGroup(painelSateliteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbIdade10)
                            .addComponent(lbIdade11)
                            .addComponent(lbAcGrav10)
                            .addComponent(lbDiametro10)
                            .addComponent(lbVolume10)
                            .addComponent(lbTemperatura10)
                            .addComponent(lbVelocidade10)
                            .addComponent(lbGalaxia10)
                            .addComponent(lbMassa10))
                        .addGap(26, 26, 26)
                        .addGroup(painelSateliteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNome80)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSateliteLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(painelSateliteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfAcelDiametro, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                                    .addComponent(tfDiametro)
                                    .addComponent(tfVolume)
                                    .addComponent(tfVelocidade)
                                    .addComponent(tfTemperatura)))
                            .addComponent(tfMassa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfGalaxia)
                            .addComponent(tfIdade, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSateliteLayout.createSequentialGroup()
                        .addComponent(jrbArtificial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbVoltar)))
                .addContainerGap())
        );
        painelSateliteLayout.setVerticalGroup(
            painelSateliteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSateliteLayout.createSequentialGroup()
                .addGroup(painelSateliteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelSateliteLayout.createSequentialGroup()
                        .addComponent(jbVoltar)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSateliteLayout.createSequentialGroup()
                        .addComponent(jrbArtificial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(painelSateliteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome10)
                    .addComponent(tfNome72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(painelSateliteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelSateliteLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lbEspLuz10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSateliteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNome70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(painelSateliteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelSateliteLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lbGalaxia10)
                        .addGap(26, 26, 26)
                        .addComponent(lbMassa10)
                        .addGap(26, 26, 26)
                        .addComponent(lbTemperatura10)
                        .addGap(26, 26, 26)
                        .addComponent(lbVelocidade10)
                        .addGap(29, 29, 29)
                        .addComponent(lbVolume10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbDiametro10)
                        .addGap(19, 19, 19)
                        .addComponent(lbAcGrav10)
                        .addGap(26, 26, 26)
                        .addComponent(lbIdade10))
                    .addGroup(painelSateliteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfGalaxia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(tfMassa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(tfVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(tfVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfDiametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(tfAcelDiametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(painelSateliteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdade11)
                    .addComponent(tfNome80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelSatelite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelSatelite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        // TODO add your handling code here:
        FormaSistemaSolar frame = new FormaSistemaSolar();
        frame.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jbVoltarActionPerformed

    private void jrbArtificialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbArtificialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbArtificialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaSatelite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaSatelite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaSatelite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaSatelite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaSatelite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbVoltar;
    private javax.swing.JRadioButton jrbArtificial;
    private javax.swing.JLabel lbAcGrav10;
    private javax.swing.JLabel lbDiametro10;
    private javax.swing.JLabel lbEspLuz10;
    private javax.swing.JLabel lbGalaxia10;
    private javax.swing.JLabel lbIdade10;
    private javax.swing.JLabel lbIdade11;
    private javax.swing.JLabel lbMassa10;
    private javax.swing.JLabel lbNome10;
    private javax.swing.JLabel lbTemperatura10;
    private javax.swing.JLabel lbVelocidade10;
    private javax.swing.JLabel lbVolume10;
    private javax.swing.JPanel painelSatelite;
    private javax.swing.JTextField tfAcelDiametro;
    private javax.swing.JTextField tfDiametro;
    private javax.swing.JTextField tfGalaxia;
    private javax.swing.JTextField tfIdade;
    private javax.swing.JTextField tfMassa;
    private javax.swing.JTextField tfNome70;
    private javax.swing.JTextField tfNome72;
    private javax.swing.JTextField tfNome80;
    private javax.swing.JTextField tfTemperatura;
    private javax.swing.JTextField tfVelocidade;
    private javax.swing.JTextField tfVolume;
    // End of variables declaration//GEN-END:variables
}
