/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author davidson
 */
public class FormaSistemaSolar extends javax.swing.JFrame {

    /**
     * Creates new form FormaSistemaSolar
     */
    public FormaSistemaSolar() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnSisSolar = new javax.swing.JPanel();
        btEstrela = new javax.swing.JButton();
        btSatelite = new javax.swing.JButton();
        btAsteroide = new javax.swing.JButton();
        btEstacaoEspacial = new javax.swing.JButton();
        btPlus = new javax.swing.JButton();
        btPlaneta3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnSisSolar.setBackground(new java.awt.Color(1, 1, 1));
        pnSisSolar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bem Vindo ao Sistema Solar", 0, 0, new java.awt.Font("Ubuntu", 0, 18), new java.awt.Color(254, 254, 254))); // NOI18N
        pnSisSolar.setForeground(new java.awt.Color(254, 254, 254));

        btEstrela.setText("Estrela");
        btEstrela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEstrelaActionPerformed(evt);
            }
        });

        btSatelite.setText("Satélite");
        btSatelite.setToolTipText("");
        btSatelite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSateliteActionPerformed(evt);
            }
        });

        btAsteroide.setText("Asteroide");
        btAsteroide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAsteroideActionPerformed(evt);
            }
        });

        btEstacaoEspacial.setText("Estação Espacial");
        btEstacaoEspacial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEstacaoEspacialActionPerformed(evt);
            }
        });

        btPlus.setText("Informar");
        btPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPlusActionPerformed(evt);
            }
        });

        btPlaneta3.setText("Planeta");
        btPlaneta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPlaneta3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnSisSolarLayout = new javax.swing.GroupLayout(pnSisSolar);
        pnSisSolar.setLayout(pnSisSolarLayout);
        pnSisSolarLayout.setHorizontalGroup(
            pnSisSolarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSisSolarLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(pnSisSolarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btEstrela, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(btPlaneta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(79, 79, 79)
                .addGroup(pnSisSolarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btEstacaoEspacial, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(btSatelite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(78, 78, 78)
                .addGroup(pnSisSolarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btAsteroide, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        pnSisSolarLayout.setVerticalGroup(
            pnSisSolarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSisSolarLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnSisSolarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSatelite, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAsteroide, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPlaneta3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(pnSisSolarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEstrela, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEstacaoEspacial, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnSisSolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnSisSolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAsteroideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAsteroideActionPerformed
    // TODO add your handling code here:
        FormaAsteroide frame = new FormaAsteroide();  
        frame.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btAsteroideActionPerformed

    private void btSateliteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSateliteActionPerformed
        // TODO add your handling code here:
        FormaSatelite frame = new FormaSatelite();  
        frame.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btSateliteActionPerformed

    private void btPlaneta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPlaneta3ActionPerformed
        // TODO add your handling code here:
        FormaPlaneta frame = new FormaPlaneta();  
        frame.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btPlaneta3ActionPerformed

    private void btEstrelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEstrelaActionPerformed
        // TODO add your handling code here:
        FormaEstrela frame = new FormaEstrela();  
        frame.setVisible(true);
    }//GEN-LAST:event_btEstrelaActionPerformed

    private void btEstacaoEspacialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEstacaoEspacialActionPerformed
        // TODO add your handling code here:
        FormaEstacaoEspacial frame = new FormaEstacaoEspacial();  
        frame.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btEstacaoEspacialActionPerformed

    private void btPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPlusActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(rootPane, "Planeta 1: \n"
        //        + "Nome: " + 
        // );
    }//GEN-LAST:event_btPlusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaSistemaSolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaSistemaSolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaSistemaSolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaSistemaSolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaSistemaSolar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAsteroide;
    private javax.swing.JButton btEstacaoEspacial;
    private javax.swing.JButton btEstrela;
    private javax.swing.JButton btPlaneta3;
    private javax.swing.JButton btPlus;
    private javax.swing.JButton btSatelite;
    private javax.swing.JPanel pnSisSolar;
    // End of variables declaration//GEN-END:variables
}
