/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sistemasolar.Asteroide;


/**
 *
 * @author Bruno
 */
public class FormaAsteroide extends javax.swing.JFrame {

    /**
     * Creates new form FormaAsteroide
     */
    public FormaAsteroide() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelAsteroide = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        lbEspLuz = new javax.swing.JLabel();
        lbGalaxia = new javax.swing.JLabel();
        lbMassa = new javax.swing.JLabel();
        lbTemperatura = new javax.swing.JLabel();
        lbVelocidade = new javax.swing.JLabel();
        lbVolume = new javax.swing.JLabel();
        lbDiametro = new javax.swing.JLabel();
        lbAcGrav = new javax.swing.JLabel();
        lbIdade = new javax.swing.JLabel();
        tfEdL = new javax.swing.JTextField();
        tfGalaxia = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        tfMassa = new javax.swing.JTextField();
        tfTemperatura = new javax.swing.JTextField();
        tfVolume = new javax.swing.JTextField();
        tfVelocidade = new javax.swing.JTextField();
        tfDiametro = new javax.swing.JTextField();
        tfAcelGrav = new javax.swing.JTextField();
        tfIdade = new javax.swing.JTextField();
        lbRisco = new javax.swing.JLabel();
        tfRisco = new javax.swing.JTextField();
        lbClasse = new javax.swing.JLabel();
        tfClasse = new javax.swing.JTextField();
        jbVoltar = new javax.swing.JButton();
        jbConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelAsteroide.setBackground(new java.awt.Color(208, 208, 208));
        painelAsteroide.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Asteróide", 0, 0, new java.awt.Font("Ubuntu", 0, 18))); // NOI18N

        lbNome.setText("Nome:");

        lbEspLuz.setText("Espectro de luz:");

        lbGalaxia.setText("Galaxia:");

        lbMassa.setText(" Massa:");

        lbTemperatura.setText("Temperatura:");

        lbVelocidade.setText("Velocidade:");

        lbVolume.setText("Volume:");

        lbDiametro.setText("Diâmetro:");

        lbAcGrav.setText("Acel da Gravidade:");

        lbIdade.setText("Idade:");

        tfGalaxia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfGalaxiaActionPerformed(evt);
            }
        });

        tfTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTemperaturaActionPerformed(evt);
            }
        });

        lbRisco.setText("Risco:");

        lbClasse.setText("Classe:");

        jbVoltar.setText("Voltar");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });

        jbConfirmar.setText("Confirmar");
        jbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelAsteroideLayout = new javax.swing.GroupLayout(painelAsteroide);
        painelAsteroide.setLayout(painelAsteroideLayout);
        painelAsteroideLayout.setHorizontalGroup(
            painelAsteroideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAsteroideLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(painelAsteroideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelAsteroideLayout.createSequentialGroup()
                        .addComponent(lbAcGrav)
                        .addGap(43, 43, 43)
                        .addComponent(tfAcelGrav, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE))
                    .addGroup(painelAsteroideLayout.createSequentialGroup()
                        .addComponent(lbEspLuz)
                        .addGap(58, 58, 58)
                        .addComponent(tfEdL))
                    .addGroup(painelAsteroideLayout.createSequentialGroup()
                        .addComponent(lbGalaxia)
                        .addGap(116, 116, 116)
                        .addComponent(tfGalaxia))
                    .addGroup(painelAsteroideLayout.createSequentialGroup()
                        .addComponent(lbNome)
                        .addGap(123, 123, 123)
                        .addComponent(tfNome))
                    .addGroup(painelAsteroideLayout.createSequentialGroup()
                        .addComponent(lbMassa)
                        .addGap(119, 119, 119)
                        .addComponent(tfMassa))
                    .addGroup(painelAsteroideLayout.createSequentialGroup()
                        .addComponent(lbTemperatura)
                        .addGap(73, 73, 73)
                        .addComponent(tfTemperatura))
                    .addGroup(painelAsteroideLayout.createSequentialGroup()
                        .addComponent(lbVolume)
                        .addGap(112, 112, 112)
                        .addComponent(tfVolume))
                    .addGroup(painelAsteroideLayout.createSequentialGroup()
                        .addComponent(lbVelocidade)
                        .addGap(88, 88, 88)
                        .addComponent(tfVelocidade))
                    .addGroup(painelAsteroideLayout.createSequentialGroup()
                        .addComponent(lbDiametro)
                        .addGap(100, 100, 100)
                        .addComponent(tfDiametro))
                    .addGroup(painelAsteroideLayout.createSequentialGroup()
                        .addGroup(painelAsteroideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbIdade)
                            .addComponent(lbRisco)
                            .addComponent(lbClasse))
                        .addGap(120, 120, 120)
                        .addGroup(painelAsteroideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfIdade)
                            .addComponent(tfRisco)
                            .addComponent(tfClasse, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAsteroideLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbConfirmar)
                .addGap(18, 18, 18)
                .addComponent(jbVoltar)
                .addContainerGap())
        );
        painelAsteroideLayout.setVerticalGroup(
            painelAsteroideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAsteroideLayout.createSequentialGroup()
                .addGroup(painelAsteroideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbVoltar)
                    .addComponent(jbConfirmar))
                .addGap(12, 12, 12)
                .addGroup(painelAsteroideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(painelAsteroideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEspLuz)
                    .addComponent(tfEdL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(painelAsteroideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGalaxia)
                    .addComponent(tfGalaxia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(painelAsteroideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMassa)
                    .addComponent(tfMassa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(painelAsteroideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTemperatura)
                    .addComponent(tfTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(painelAsteroideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVelocidade)
                    .addComponent(tfVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(painelAsteroideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelAsteroideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDiametro)
                    .addComponent(tfDiametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(painelAsteroideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAcGrav)
                    .addComponent(tfAcelGrav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(painelAsteroideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdade)
                    .addComponent(tfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(painelAsteroideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRisco)
                    .addComponent(tfRisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelAsteroideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbClasse)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelAsteroide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelAsteroide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        // TODO add your handling code here:
        FormaAsteroide frameAtual = new FormaAsteroide();
        frameAtual.setVisible(false);
        FormaSistemaSolar frame = new FormaSistemaSolar();  
        frame.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jbVoltarActionPerformed

    private void tfGalaxiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfGalaxiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfGalaxiaActionPerformed

    private void tfTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTemperaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTemperaturaActionPerformed

    private void jbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarActionPerformed
        //capturar texto
        String nome = tfNome.getText();
        String edl = tfEdL.getText();
        String gal = tfGalaxia.getText();
        String massa = tfMassa.getText();
        String temperatura = tfTemperatura.getText();
        String velocidade = tfVelocidade.getText();
        String volume = tfVolume.getText();
        String diametro = tfDiametro.getText();
        String acelGrav = tfAcelGrav.getText();
        String idade = tfIdade.getText();
        String risco = tfRisco.getText();
        String classe = tfClasse.getText();
        //cria objeto de Asteroide
        Asteroide a1 = new Asteroide(Double.parseDouble(risco), classe,
            nome, edl, gal, Double.parseDouble(massa), Double.parseDouble(temperatura),
            Double.parseDouble(velocidade), Double.parseDouble(volume), Double.parseDouble(diametro),
            Double.parseDouble(acelGrav), Integer.parseInt(idade));
        
        FileWriter filer;
        BufferedWriter buff;
        
        
        try {
            filer  = new FileWriter("asteroide.txt");
            buff  = new BufferedWriter(filer);
            buff.write(nome+edl+gal+
              Double.parseDouble(massa)+ Double.parseDouble(temperatura)+
            Double.parseDouble(velocidade)+ Double.parseDouble(volume)+ Double.parseDouble(diametro)+
            Double.parseDouble(acelGrav)+ Integer.parseInt(idade)+ Double.parseDouble(risco)+ classe);
            buff.close();
            
   
            
        } catch (IOException ex) {
            Logger.getLogger(FormaAsteroide.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
     
        
        //imprime
        JOptionPane.showMessageDialog(rootPane, "Asteroide 1: \n"
            +"\nNome: "+a1.getNome()
            +"\nEspectro de Luz: "+a1.getEspectroDeLuz()
            +"\nGaláxia: "+a1.getGalaxia()
            +"\nMassa: "+a1.getMassa()+" t."
            +"\nTemperatura Média: "+a1.getTemperatura()+" ºC."
            +"\nVelocidade de órbita: "+a1.getVelocidade()+ "km/h."
            +"\nVolume: "+a1.getVolume()+" km³."
            +"\nDiâmetro: "+a1.getDiametro()+" km."
            +"\nAceleração da Gravidade: "+a1.getAcelGravidade()+" m/s²."
            +"\nIdade: "+a1.getIdade()+" anos.\n"
            +"\nRisco de Atingir a Terra: "+a1.getRisco()
            +"\nClasse: "+a1.getClasse()+"\n\n"
        );
    }//GEN-LAST:event_jbConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaAsteroide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaAsteroide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaAsteroide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaAsteroide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaAsteroide().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbConfirmar;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JLabel lbAcGrav;
    private javax.swing.JLabel lbClasse;
    private javax.swing.JLabel lbDiametro;
    private javax.swing.JLabel lbEspLuz;
    private javax.swing.JLabel lbGalaxia;
    private javax.swing.JLabel lbIdade;
    private javax.swing.JLabel lbMassa;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbRisco;
    private javax.swing.JLabel lbTemperatura;
    private javax.swing.JLabel lbVelocidade;
    private javax.swing.JLabel lbVolume;
    private javax.swing.JPanel painelAsteroide;
    private javax.swing.JTextField tfAcelGrav;
    private javax.swing.JTextField tfClasse;
    private javax.swing.JTextField tfDiametro;
    private javax.swing.JTextField tfEdL;
    private javax.swing.JTextField tfGalaxia;
    private javax.swing.JTextField tfIdade;
    private javax.swing.JTextField tfMassa;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfRisco;
    private javax.swing.JTextField tfTemperatura;
    private javax.swing.JTextField tfVelocidade;
    private javax.swing.JTextField tfVolume;
    // End of variables declaration//GEN-END:variables
}
