/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sistemasolar.Estrela;

/**
 *
 * @author davidson
 */
public class FormaEstrela extends javax.swing.JFrame {

    /**
     * Creates new form FormaEstrela
     */
    public FormaEstrela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelEstrela = new javax.swing.JPanel();
        lbNome10 = new javax.swing.JLabel();
        lbEspLuz10 = new javax.swing.JLabel();
        lbGalaxia10 = new javax.swing.JLabel();
        lbMassa10 = new javax.swing.JLabel();
        lbTemperatura10 = new javax.swing.JLabel();
        lbVelocidade10 = new javax.swing.JLabel();
        lbVolume10 = new javax.swing.JLabel();
        lbDiametro10 = new javax.swing.JLabel();
        lbAcGrav10 = new javax.swing.JLabel();
        lbIdade10 = new javax.swing.JLabel();
        tfEdL = new javax.swing.JTextField();
        tfGalaxia = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        tfMassa = new javax.swing.JTextField();
        tfTemperatura = new javax.swing.JTextField();
        tfVolume = new javax.swing.JTextField();
        tfVelocidade = new javax.swing.JTextField();
        tfDiametro = new javax.swing.JTextField();
        tfAcelGrav = new javax.swing.JTextField();
        tfIdade = new javax.swing.JTextField();
        lbIdade11 = new javax.swing.JLabel();
        tfTpTrans = new javax.swing.JTextField();
        lbIdade12 = new javax.swing.JLabel();
        tfTpRotacao = new javax.swing.JTextField();
        jbVoltar = new javax.swing.JButton();
        lbKp = new javax.swing.JLabel();
        lbFluxo = new javax.swing.JLabel();
        lbManchas = new javax.swing.JLabel();
        lbEmc = new javax.swing.JLabel();
        tfEmc = new javax.swing.JTextField();
        tfManchas = new javax.swing.JTextField();
        tfFluxo = new javax.swing.JTextField();
        tfKp = new javax.swing.JTextField();
        jbConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelEstrela.setBackground(new java.awt.Color(208, 208, 208));
        painelEstrela.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estrela", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 18))); // NOI18N

        lbNome10.setText("Nome:");

        lbEspLuz10.setText("Espectro de luz:");

        lbGalaxia10.setText("Galaxia:");

        lbMassa10.setText(" Massa:");

        lbTemperatura10.setText("Temperatura:");

        lbVelocidade10.setText("Velocidade:");

        lbVolume10.setText("Volume:");

        lbDiametro10.setText("Diâmetro:");

        lbAcGrav10.setText("Acel da Gravidade:");

        lbIdade10.setText("Idade:");

        lbIdade11.setText("Tempo de Translação:");

        lbIdade12.setText("Tempo de Rotação:");

        jbVoltar.setText("Voltar");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });

        lbKp.setText("Kp:");

        lbFluxo.setText("Fluxo:");

        lbManchas.setText("Manchas:");

        lbEmc.setText("Emc:");

        jbConfirmar.setText("Confirmar");
        jbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelEstrelaLayout = new javax.swing.GroupLayout(painelEstrela);
        painelEstrela.setLayout(painelEstrelaLayout);
        painelEstrelaLayout.setHorizontalGroup(
            painelEstrelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEstrelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEstrelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelEstrelaLayout.createSequentialGroup()
                        .addGroup(painelEstrelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbIdade12)
                            .addComponent(lbKp)
                            .addComponent(lbFluxo)
                            .addComponent(lbManchas)
                            .addComponent(lbEmc))
                        .addGap(49, 49, 49)
                        .addGroup(painelEstrelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfEmc, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                            .addComponent(tfManchas)
                            .addComponent(tfFluxo)
                            .addComponent(tfKp)
                            .addComponent(tfTpRotacao)))
                    .addGroup(painelEstrelaLayout.createSequentialGroup()
                        .addComponent(lbNome10)
                        .addGap(136, 136, 136)
                        .addComponent(tfNome))
                    .addGroup(painelEstrelaLayout.createSequentialGroup()
                        .addComponent(lbIdade10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addGroup(painelEstrelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfIdade)
                            .addComponent(tfTpTrans)))
                    .addGroup(painelEstrelaLayout.createSequentialGroup()
                        .addComponent(lbAcGrav10, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(tfAcelGrav))
                    .addGroup(painelEstrelaLayout.createSequentialGroup()
                        .addComponent(lbDiametro10, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(tfDiametro))
                    .addGroup(painelEstrelaLayout.createSequentialGroup()
                        .addComponent(lbVolume10)
                        .addGap(125, 125, 125)
                        .addComponent(tfVolume))
                    .addGroup(painelEstrelaLayout.createSequentialGroup()
                        .addComponent(lbVelocidade10)
                        .addGap(101, 101, 101)
                        .addComponent(tfVelocidade))
                    .addGroup(painelEstrelaLayout.createSequentialGroup()
                        .addComponent(lbTemperatura10)
                        .addGap(86, 86, 86)
                        .addComponent(tfTemperatura))
                    .addGroup(painelEstrelaLayout.createSequentialGroup()
                        .addComponent(lbMassa10)
                        .addGap(132, 132, 132)
                        .addComponent(tfMassa))
                    .addGroup(painelEstrelaLayout.createSequentialGroup()
                        .addComponent(lbGalaxia10)
                        .addGap(129, 129, 129)
                        .addComponent(tfGalaxia))
                    .addGroup(painelEstrelaLayout.createSequentialGroup()
                        .addComponent(lbEspLuz10)
                        .addGap(71, 71, 71)
                        .addComponent(tfEdL))
                    .addGroup(painelEstrelaLayout.createSequentialGroup()
                        .addComponent(lbIdade11, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelEstrelaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbConfirmar)
                        .addGap(18, 18, 18)
                        .addComponent(jbVoltar)))
                .addContainerGap())
        );
        painelEstrelaLayout.setVerticalGroup(
            painelEstrelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEstrelaLayout.createSequentialGroup()
                .addGroup(painelEstrelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbVoltar)
                    .addComponent(jbConfirmar))
                .addGap(12, 12, 12)
                .addGroup(painelEstrelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome10)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(painelEstrelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEspLuz10)
                    .addComponent(tfEdL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(painelEstrelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGalaxia10)
                    .addComponent(tfGalaxia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(painelEstrelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMassa10)
                    .addComponent(tfMassa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(painelEstrelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTemperatura10)
                    .addComponent(tfTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(painelEstrelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVelocidade10)
                    .addComponent(tfVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(painelEstrelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVolume10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelEstrelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDiametro10)
                    .addComponent(tfDiametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(painelEstrelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAcGrav10)
                    .addComponent(tfAcelGrav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(painelEstrelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdade10)
                    .addComponent(tfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelEstrelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdade11)
                    .addComponent(tfTpTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelEstrelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdade12)
                    .addComponent(tfTpRotacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelEstrelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbKp)
                    .addComponent(tfKp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelEstrelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFluxo)
                    .addComponent(tfFluxo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelEstrelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbManchas)
                    .addComponent(tfManchas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelEstrelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmc)
                    .addComponent(tfEmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelEstrela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelEstrela, javax.swing.GroupLayout.PREFERRED_SIZE, 721, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        // TODO add your handling code here:
        FormaSistemaSolar frame = new FormaSistemaSolar();
        frame.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jbVoltarActionPerformed

    private void jbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarActionPerformed
        //capturar texto
        String nome = tfNome.getText();
        String edl = tfEdL.getText();
        String gal = tfGalaxia.getText();
        String massa = tfMassa.getText();
        String temperatura = tfTemperatura.getText();
        String velocidade = tfVelocidade.getText();
        String volume = tfVolume.getText();
        String diametro = tfDiametro.getText();
        String acelGrav = tfAcelGrav.getText();
        String idade = tfIdade.getText();
        String tpTranslacao = tfTpTrans.getText();
        String tpRot = tfTpRotacao.getText();
        String kp = tfKp.getText();
        String fluxo = tfFluxo.getText();
        String manchas = tfManchas.getText();
        String emc = tfEmc.getText();
        //cria objeto de Planeta
        Estrela est1 = new Estrela(Double.parseDouble(tpTranslacao), Double.parseDouble(tpRot), Integer.parseInt(kp),
                Double.parseDouble(fluxo), Integer.parseInt(manchas),Boolean.parseBoolean(emc),nome, edl,
                gal, Double.parseDouble(massa), Double.parseDouble(temperatura), 
                Double.parseDouble(velocidade), Double.parseDouble(volume), Double.parseDouble(diametro),
                Double.parseDouble(acelGrav), Integer.parseInt(idade));

        //imprime
        JOptionPane.showMessageDialog(rootPane, "Estrela: \n"
            +"\nNome: "+est1.getNome()
            +"\nEspectro de Luz: "+est1.getEspectroDeLuz()
            +"\nGaláxia: "+est1.getGalaxia()
            +"\nMassa: "+est1.getMassa()+" t."
            +"\nTemperatura Média: "+est1.getTemperatura()+" ºC."
            +"\nVelocidade de órbita: "+est1.getVelocidade()+ "km/h."
            +"\nVolume: "+est1.getVolume()+" km³."
            +"\nDiâmetro: "+est1.getDiametro()+" km."
            +"\nAceleração da Gravidade: "+est1.getAcelGravidade()+" m/s²."
            +"\nIdade: "+est1.getIdade()+" anos.\n"
            +"\nTempo de Translação: "+est1.getTpTranslacao()+" milhões de anos em relação ao centro da galáxia."
            +"\nTempo de Rotação: "+est1.getTpRotacao()+" dias na linha do equador."
            +"\nEjeção de Massa Coronal: "+est1.isEmc()
            +"\nIntensidade de EMC: "+est1.getKp()
            +"\nFluxo de Raios X: "+est1.getFluxo()
            +"\nManchas: "+est1.getManchas()+"\n\n"
        );
        
        FileWriter filer;
        BufferedWriter buff;
        
        
        try {
            filer  = new FileWriter("estrela.txt");
            buff  = new BufferedWriter(filer);
            buff.write(est1.getNome()+est1.getEspectroDeLuz()+est1.getGalaxia()+est1.getMassa()+ est1.getTemperatura()+est1.getVelocidade()+est1.getVolume()+est1.getDiametro()+est1.getAcelGravidade()
            +est1.getIdade()+est1.getTpTranslacao()+est1.getTpRotacao()+est1.isEmc()+est1.getKp()+est1.getFluxo()+est1.getManchas());
            buff.close();
            
   
            
        } catch (IOException ex) {
            Logger.getLogger(FormaEstrela.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
        
    }//GEN-LAST:event_jbConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaEstrela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaEstrela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaEstrela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaEstrela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaEstrela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbConfirmar;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JLabel lbAcGrav10;
    private javax.swing.JLabel lbDiametro10;
    private javax.swing.JLabel lbEmc;
    private javax.swing.JLabel lbEspLuz10;
    private javax.swing.JLabel lbFluxo;
    private javax.swing.JLabel lbGalaxia10;
    private javax.swing.JLabel lbIdade10;
    private javax.swing.JLabel lbIdade11;
    private javax.swing.JLabel lbIdade12;
    private javax.swing.JLabel lbKp;
    private javax.swing.JLabel lbManchas;
    private javax.swing.JLabel lbMassa10;
    private javax.swing.JLabel lbNome10;
    private javax.swing.JLabel lbTemperatura10;
    private javax.swing.JLabel lbVelocidade10;
    private javax.swing.JLabel lbVolume10;
    private javax.swing.JPanel painelEstrela;
    private javax.swing.JTextField tfAcelGrav;
    private javax.swing.JTextField tfDiametro;
    private javax.swing.JTextField tfEdL;
    private javax.swing.JTextField tfEmc;
    private javax.swing.JTextField tfFluxo;
    private javax.swing.JTextField tfGalaxia;
    private javax.swing.JTextField tfIdade;
    private javax.swing.JTextField tfKp;
    private javax.swing.JTextField tfManchas;
    private javax.swing.JTextField tfMassa;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfTemperatura;
    private javax.swing.JTextField tfTpRotacao;
    private javax.swing.JTextField tfTpTrans;
    private javax.swing.JTextField tfVelocidade;
    private javax.swing.JTextField tfVolume;
    // End of variables declaration//GEN-END:variables
}
